Traceback (most recent call last):
  File "/Users/jpnelson/02021/sul-dlss/labs/ml-env/lib/python3.9/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/Users/jpnelson/02021/sul-dlss/labs/ml-env/lib/python3.9/site-packages/nbclient/client.py", line 1112, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/Users/jpnelson/02021/sul-dlss/labs/ml-env/lib/python3.9/site-packages/nbclient/util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/Users/jpnelson/02021/sul-dlss/labs/ml-env/lib/python3.9/site-packages/nbclient/util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/Users/jpnelson/02021/sul-dlss/labs/ml-env/lib/python3.9/site-packages/nbclient/client.py", line 553, in async_execute
    await self.async_execute_cell(
  File "/Users/jpnelson/02021/sul-dlss/labs/ml-env/lib/python3.9/site-packages/nbclient/client.py", line 857, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/Users/jpnelson/02021/sul-dlss/labs/ml-env/lib/python3.9/site-packages/nbclient/client.py", line 760, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
client = grobid.grobid_client(config_path="./grobid_config.json")
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mFileNotFoundError[0m                         Traceback (most recent call last)
[0;32m<ipython-input-4-ef3304f74194>[0m in [0;36m<module>[0;34m[0m
[0;32m----> 1[0;31m [0mclient[0m [0;34m=[0m [0mgrobid[0m[0;34m.[0m[0mgrobid_client[0m[0;34m([0m[0mconfig_path[0m[0;34m=[0m[0;34m"./grobid_config.json"[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m
[0;32m~/02021/sul-dlss/labs/grobid_client_python/grobid_client.py[0m in [0;36m__init__[0;34m(self, config_path)[0m
[1;32m     23[0m     [0;32mdef[0m [0m__init__[0m[0;34m([0m[0mself[0m[0;34m,[0m [0mconfig_path[0m[0;34m=[0m[0;34m'./config.json'[0m[0;34m)[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[1;32m     24[0m         [0mself[0m[0;34m.[0m[0mconfig[0m [0;34m=[0m [0;32mNone[0m[0;34m[0m[0;34m[0m[0m
[0;32m---> 25[0;31m         [0mself[0m[0;34m.[0m[0m_load_config[0m[0;34m([0m[0mconfig_path[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m     26[0m [0;34m[0m[0m
[1;32m     27[0m     [0;32mdef[0m [0m_load_config[0m[0;34m([0m[0mself[0m[0;34m,[0m [0mpath[0m[0;34m=[0m[0;34m'./config.json'[0m[0;34m)[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m

[0;32m~/02021/sul-dlss/labs/grobid_client_python/grobid_client.py[0m in [0;36m_load_config[0;34m(self, path)[0m
[1;32m     29[0m         [0mLoad[0m [0mthe[0m [0mjson[0m [0mconfiguration[0m[0;34m[0m[0;34m[0m[0m
[1;32m     30[0m         """
[0;32m---> 31[0;31m         [0mconfig_json[0m [0;34m=[0m [0mopen[0m[0;34m([0m[0mpath[0m[0;34m)[0m[0;34m.[0m[0mread[0m[0;34m([0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m     32[0m         [0mself[0m[0;34m.[0m[0mconfig[0m [0;34m=[0m [0mjson[0m[0;34m.[0m[0mloads[0m[0;34m([0m[0mconfig_json[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m     33[0m [0;34m[0m[0m

[0;31mFileNotFoundError[0m: [Errno 2] No such file or directory: './grobid_config.json'
FileNotFoundError: [Errno 2] No such file or directory: './grobid_config.json'

