Traceback (most recent call last):
  File "/Users/jpnelson/02021/sul-dlss/labs/ml-env/lib/python3.9/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/Users/jpnelson/02021/sul-dlss/labs/ml-env/lib/python3.9/site-packages/nbclient/client.py", line 1112, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/Users/jpnelson/02021/sul-dlss/labs/ml-env/lib/python3.9/site-packages/nbclient/util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/Users/jpnelson/02021/sul-dlss/labs/ml-env/lib/python3.9/site-packages/nbclient/util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/Users/jpnelson/02021/sul-dlss/labs/ml-env/lib/python3.9/site-packages/nbclient/client.py", line 553, in async_execute
    await self.async_execute_cell(
  File "/Users/jpnelson/02021/sul-dlss/labs/ml-env/lib/python3.9/site-packages/nbclient/client.py", line 857, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/Users/jpnelson/02021/sul-dlss/labs/ml-env/lib/python3.9/site-packages/nbclient/client.py", line 760, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
# Using PhraseMatcher
import pickle
with open("../data/scientific-names.pkl", 'rb') as fo:
    sci_names = pickle.load(fo)
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mFileNotFoundError[0m                         Traceback (most recent call last)
[0;32m<ipython-input-5-f4e0863122de>[0m in [0;36m<module>[0;34m[0m
[1;32m      1[0m [0;31m# Using PhraseMatcher[0m[0;34m[0m[0;34m[0m[0;34m[0m[0m
[1;32m      2[0m [0;32mimport[0m [0mpickle[0m[0;34m[0m[0;34m[0m[0m
[0;32m----> 3[0;31m [0;32mwith[0m [0mopen[0m[0;34m([0m[0;34m"../data/scientific-names.pkl"[0m[0;34m,[0m [0;34m'rb'[0m[0;34m)[0m [0;32mas[0m [0mfo[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m      4[0m     [0msci_names[0m [0;34m=[0m [0mpickle[0m[0;34m.[0m[0mload[0m[0;34m([0m[0mfo[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m

[0;31mFileNotFoundError[0m: [Errno 2] No such file or directory: '../data/scientific-names.pkl'
FileNotFoundError: [Errno 2] No such file or directory: '../data/scientific-names.pkl'

